# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Testaaa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Testaaa

  pod 'RAMAnimatedTabBarController', '~> 2.0.13'
  pod 'InteractiveSideMenu'
  pod 'RealmSwift'
  pod 'Alamofire', '~> 4.4'
  pod 'JTAppleCalendar', '= 6.0'
  #pod 'KRProgressHUD'
  #pod 'ObjectMapper'
  #pod 'AlamofireObjectMapper'
  #pod 'SwiftyJSON'

  target 'TestaaaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestaaaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
